[104] add prometheus metrics
HIRO-MicroDataCenters-BV/rhio pull request #110
Opened 2024-12-10 15:44 UTC by ktatarnikovhiro

2025-01-07 08:24 UTC, sandreae requested changes
I believe one change is required in the metrics reporting when receiving NATS messages.

2025-01-07 08:24 UTC, sandreae commented on rhio/src/node/actor.rs
> +                    LABEL_REMOTE_BUCKET => subject.to_string()
Nats messages aren't connected to a s3 bucket instance, they contain domain specific messages. Considering this I'm not sure that `LABEL_REMOTE_BUCKET` should be present here.

2025-01-13 11:37 UTC, Shockedshodan reviewed
Added comments

2025-01-13 11:37 UTC, Shockedshodan commented on rhio/src/blobs/actor.rs
> +                    metrics::counter!(
I'd move repeating code in a helper function to improve readability.
`    fn increment_metrics(&self, msg_type: &str, blob: &SignedBlobInfo) {
        metrics::counter!(
            BLOBS_DOWNLOAD_TOTAL,
            LABEL_MSG_TYPE => msg_type.to_owned(),
            LABEL_LOCAL_BUCKET => blob.local_bucket_name.to_owned(),
            LABEL_REMOTE_BUCKET => blob.remote_bucket_name.to_owned()
        ).increment(1);
    }`

2025-01-13 11:37 UTC, Shockedshodan commented on rhio/src/node/actor.rs
> +                    metrics::counter!(
Same logic applies to this counters too.

2025-01-13 11:37 UTC, Shockedshodan commented on rhio/src/health.rs
> +    let recorder_handle = setup_metrics_recorder()?;
You use `.context()` a bit below but don't use it there. I suggest adding context for `recorder_handle`, `listener`, `axum::serve`, etc.

2025-01-13 13:59 UTC, ktatarnikovhiro commented on rhio/src/health.rs
> +    let recorder_handle = setup_metrics_recorder()?;
fixed

2025-01-13 16:02 UTC, merged